### PR TITLE
Written tests

### PR DESCRIPTION
**Pull request by El-Potato-Slayer**
- Tests for Todo class have been written
- Tests for Category class have been written

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- [ ] Good job, on your test units :100: 

To Improve :factory_worker: (REQUIRED)

- [ ] Necessary run common commands like `build`, `development` should be in package.json inside `scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))

```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```

- [ ] As you are using ES6+, please use arrow function in your APP.
- [ ] As I can see, your inline comments are helpful and make your code easy to read, but I suggest you focus on your code and logic. Using git history can help us to understand what you have done and  to review a previous version of your code, please, feel free to remove them.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Comment by El-Potato-Slayer** [comment]
@rindrajosia You reviewed the wrong project

**Comment by El-Potato-Slayer** [comment]
@rindrajosia I have no inline comments in my test files, and some of your changes are unnecessary preferences. Changes will not be made

**Comment by rindrajosia** [comment]
> @rindrajosia I have no inline comments in my test files, and some of your changes are unnecessary preferences. Changes will not be made

Please, find attaced here screenshot of inline comments that I point out. It will be nice if you remove all of them as I already ecplained the reason:

**Comment by El-Potato-Slayer** [comment]
@rindrajosia Alright, I'll remove those comments

**Review by Torres-ssf — APPROVED** [review]
### PR Approved :hand: 
Hi @El-Potato-Slayer :hand: 
Nice job testing your application
Good luck with the next project.

Happy coding :computer: 
**Sérgio Torres**

**Comment by El-Potato-Slayer** [comment]
@Torres-ssf Sweet, dude. I'll buy you a beer and pizza sometime 👌

**Pull request merged**
